# Generated by Django 4.0 on 2021-12-26 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_message_file_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='audio_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
